### ISSUE TITLE
port husk spawn in temples

### ISSUE THREAD

**Issue by atomicmeatball** [gnembon/carpetmod#101]
i would like to have this ported to 1.13.2 i thought is was a fun new way to get sand

**Comment by Rader2146** [comment]
It’s being worked.  https://github.com/gnembon/carpetmod/pull/77

**Comment by DeadlyMC** [comment]
Remember this feature doesn't make husks drop sand. It only makes them spawn within the desert temple bounding box. If u want them to drop sand, u gotta use loot tables or datapacks

**Comment by DeadlyMC** [comment]
This issue can be closed now..Added by 19d56fd03b7d8138fa4380cc603ec95e0cc8592c

**Comment by gnembon** [comment]
merged
