### ISSUE TITLE
Cannot run dos scripts on unix based systems

### ISSUE THREAD

**Issue by ask6155** [gnembon/carpetmod#110]
The Linux install script for the server install is a shell script but it was written in a dos environment (Windows) and therefore it has dos formatting in it.
Therefore I wasn't able to run it.

I would say you write the script in the Unix format (if possible) or write it on a Unix machine.
Or you could use some kind of dos2unix converters (like I had to) to get it working.

**Comment by ask6155** [comment]
Also I would love to have a Linux client script (currently it is empty)

**Comment by gnembon** [comment]
Please feel free to submit a pull request fixing that. I know that unix distributions and different package managers use different locations to put minecraft in, so that might be an issue.

**Comment by ask6155** [comment]
that's weird, In the source code, the file is fine but in the release the file is messed up

**Comment by Earthcomputer** [comment]
This is likely caused by git's autocrlf feature. It's fixable by adding a `.gitattributes` file. I'll PR a fix.

**Comment by gnembon** [comment]
Thanks for PR's. closing
