### ISSUE TITLE
Tick freeze freezes player

### ISSUE THREAD

**Issue by wknowleskellett** [gnembon/carpetmod#118]
running '/tick freeze' on windows freezes player movement (which makes sense to me, but in a demonstration video, I saw players move during a freeze event).
This could be because I am running the mod directly on my client, so it won't let me move, whereas running carpet on a server and connecting my client to it may allow my client to continue showing movement between server-processed ticks.

**Comment by gnembon** [comment]
Yeah - that's an issue. Will look into that.
