### ISSUE TITLE
Issues Installing on windows with spaces in filepath

### ISSUE THREAD

**Issue by junnys6018** [gnembon/carpetmod#129]
Carpet mod profile failed to install because my user file has a space in it.
adding quotation marks to filepaths inside win_install_singleplayer.cmd fixed the issue.

e.g. %appdata%\.minecraft\versions\1.13.2 becomes "%appdata%\.minecraft\versions\1.13.2"

**Comment by gnembon** [comment]
Thanks, will fix that

**Comment by gnembon** [comment]
Thanks for the tip. I updated the latest release package (sunny) to fix this issue.
