### ISSUE TITLE
Skyblock related bug

### ISSUE THREAD

**Issue by Sparky164** [gnembon/carpetmod#131]
When going into the end the exit portal spawns at y-0, the pillar in the middle is there but beyond those three blocks, nothing else spawns, I've killed the dragon to see if it changes anything but I've had no result. I don't know if this is the place to put this issue but if there is a solution I would appreciate it :)

![2019-06-02_16 24 40](https://user-images.githubusercontent.com/51299954/58766977-451fc300-8553-11e9-91b4-56f2bcf75c3b.png)

**Comment by gnembon** [comment]
Sorry - wrong address. This is carpetmod, not even farbric-carpet for that matter. You might need to report that issue on https://github.com/DeadlyMC/QuickCarpet114
