### ISSUE TITLE
Block update order issue

### ISSUE THREAD

**Issue by NWindy5** [gnembon/carpetmod#20]
Block update order are not the same as vanilla thus make some contraptions broken
specifically slime block structure and piston

**Comment by gnembon** [comment]
Hmm, can you send a sample world download? I don't think I have touched updates in any shape or form so far, but I would definitely investigate and see what happens. Note that updates are now very locational for certain things and many contraptions act differently depending where they are built.

**Comment by NWindy5** [comment]
I found this issue when I was experimenting with ilmango's diagonal flying machine which is broken in carpetmod

**Comment by NWindy5** [comment]
I did some more test. There's no problem now.
Maybe it's because I built it incorrectly.
