### ISSUE TITLE
Incorrect description in carpet list

### ISSUE THREAD

**Issue by sixwheeledbeast** [gnembon/carpetmod#21]
Use /carpet list to show a list of features in chat.
Mouse over "renewableCoral" to find incorrect description.
Also note that "cashing strategy" should probably read "caching" unless this is intended.

**Comment by DeadlyMC** [comment]
Its an easy fix but @gnembon needs to specify the description he wants :P

**Comment by gnembon** [comment]
thanks for spotting that, fixed.
