### ISSUE TITLE
build failed on Windows

### ISSUE THREAD

**Issue by Yggdraszil** [gnembon/carpetmod#50]
log:

> Task :carpetmod:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':carpetmod:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 52s
7 actionable tasks: 1 executed, 6 up-to-date

**Comment by Earthcomputer** [comment]
Can you show the compiler error output?

**Comment by Yggdraszil** [comment]
Sure thing.
[Here](https://pastebin.com/hee0zTNn) is the pastebin.

**Comment by rejec7** [comment]
I've got the same error on Ubuntu as well.

**Comment by Earthcomputer** [comment]
Ah you have a BlockStateFlatteningMap issue. Try allocating more RAM to the decompiler. If that doesn't help, try getting a copy of BlockStateFlatteningMap from someone else. The decompiler always struggles with that file, it has a giant-ass method.

**Comment by Yggdraszil** [comment]
@Earthcomputer 
Thanks for your response, I managed to compile the newer version successfully.
