### ISSUE TITLE
what does this do?

### ISSUE THREAD

**Issue by bannanasareyummy** [gnembon/carpetmod#92]
I don't know what this does, can someone tell me?

**Comment by gnembon** [comment]
define 'this'?

**Comment by DeadlyMC** [comment]
Yeh, What does what do?

**Comment by SirFireNewt** [comment]
It would be nice if the wiki/readme/whatever had a list of all commands, syntax, and what they do along with a list of other features for the layman to read through to better understand this tool

at least that's what I assume op want's

**Comment by gnembon** [comment]
that might be good to have, however typing '/carpet list' or '/carpet <featureName>' provides this functionality in game. I should add that to the readme then.

**Comment by gnembon** [comment]
I added a mention of these help options in the readme. Consider it resolved than.
