### ISSUE TITLE
watchdogCrashFix is completely useless and redundant

### ISSUE THREAD

**Issue by Cynosphere** [gnembon/carpetmod#93]
`max-tick-time=-1 - disable watchdog entirely (this disable option was added in 14w32a)`

**Comment by DeadlyMC** [comment]
I don't really get it...
Can u describe it more well?

**Comment by Cynosphere** [comment]
The watchdogCrashFix option is redundant because you can just set max-tick-time in server.properties to -1 to disable it

**Comment by Earthcomputer** [comment]
The watchdogCrashFix is not redundant. With the fix, the server still crashes if it actually stops. The crash fix just stops the server crashing at less than 4tps.

**Comment by gnembon** [comment]
yep
